// THE BEER LICENSE (with extra fizz)
//
// Author: OpenAI Codex (controlled by jens@bennerhq.com)
// This code is open source with no restrictions. Wild, right?
// If this code helps, buy Jens a beer. Or two. Or a keg.
// If it fails, keep the beer and blame the LLM gremlins.
//
// Cheers!

#include "codegen_emitter_runtime.h"

#include <cstdint>
#include <ostream>
#include <string>
#include <unordered_map>

void
EmitRuntime(std::ostream &out,
            const std::unordered_map<std::string, int64_t> &string_offsets) {
  const int kIovecPtr = 0;
  const int kNwrittenPtr = 8;
  const int kBufPtr = 64;
  const int kFracBufPtr = 192;
  int64_t nl_ptr = string_offsets.at("\n");
  (void)string_offsets.at(".");
  (void)string_offsets.at("-");
  (void)string_offsets.at("+");
  (void)string_offsets.at("e");
  (void)string_offsets.at("0");
  int64_t true_ptr = string_offsets.at("true");
  int64_t false_ptr = string_offsets.at("false");

  out << "  (func $write_bytes (param $ptr i32) (param $len i32)\n";
  out << "    i32.const " << kIovecPtr << "\n";
  out << "    local.get $ptr\n";
  out << "    i32.store\n";
  out << "    i32.const " << (kIovecPtr + 4) << "\n";
  out << "    local.get $len\n";
  out << "    i32.store\n";
  out << "    i32.const 1\n";
  out << "    i32.const " << kIovecPtr << "\n";
  out << "    i32.const 1\n";
  out << "    i32.const " << kNwrittenPtr << "\n";
  out << "    call $fd_write\n";
  out << "    drop\n";
  out << "  )\n";

  out << "  (func $write_byte (param $val i32)\n";
  out << "    i32.const "<< kBufPtr << "\n";
  out << "    local.get $val\n";
  out << "    i32.store8\n";
  out << "    i32.const " << kBufPtr << "\n";
  out << "    i32.const 1\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_string_raw (param $ptr i64)\n";
  out << "    (local $len i64)\n";
  out << "    local.get $ptr\n";
  out << "    i32.wrap_i64\n";
  out << "    i64.load\n";
  out << "    local.set $len\n";
  out << "    local.get $ptr\n";
  out << "    i64.const 8\n";
  out << "    i64.add\n";
  out << "    i32.wrap_i64\n";
  out << "    local.get $len\n";
  out << "    i32.wrap_i64\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_string (param $ptr i64)\n";
  out << "    local.get $ptr\n";
  out << "    call $print_string_raw\n";
  out << "    i32.const " << (nl_ptr + 8) << "\n";
  out << "    i32.const 1\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_bool_raw (param $val i64)\n";
  out << "    local.get $val\n";
  out << "    i64.const 0\n";
  out << "    i64.ne\n";
  out << "    if\n";
  out << "      i32.const " << (true_ptr + 8) << "\n";
  out << "      i32.const 4\n";
  out << "      call $write_bytes\n";
  out << "    else\n";
  out << "      i32.const " << (false_ptr + 8) << "\n";
  out << "      i32.const 5\n";
  out << "      call $write_bytes\n";
  out << "    end\n";
  out << "  )\n";

  out << "  (func $print_bool (param $val i64)\n";
  out << "    local.get $val\n";
  out << "    call $print_bool_raw\n";
  out << "    i32.const " << (nl_ptr + 8) << "\n";
  out << "    i32.const 1\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_i64_raw (param $val i64)\n";
  out << "    (local $tmp i64) (local $pos i32) (local $neg i32) (local $digit i64)\n";
  out << "    i32.const " << (kBufPtr + 63) << "\n";
  out << "    local.set $pos\n";
  out << "    local.get $val\n";
  out << "    i64.const 0\n";
  out << "    i64.lt_s\n";
  out << "    if\n";
  out << "      i32.const 1\n local.set $neg\n";
  out << "      local.get $val\n i64.const -1\n i64.mul\n local.set $tmp\n";
  out << "    else\n";
  out << "      i32.const 0\n local.set $neg\n";
  out << "      local.get $val\n local.set $tmp\n";
  out << "    end\n";
  out << "    local.get $tmp\n i64.const 0\n i64.eq\n";
  out << "    if\n";
  out << "      local.get $pos\n i32.const 48\n i32.store8\n";
  out << "      local.get $pos\n i32.const 1\n i32.sub\n local.set $pos\n";
  out << "    else\n";
  out << "      block\n loop\n";
  out << "          local.get $tmp\n i64.const 0\n i64.eq\n br_if 1\n";
  out << "          local.get $tmp\n i64.const 10\n i64.rem_u\n local.set $digit\n";
  out << "          local.get $pos\n local.get $digit\n i64.const 48\n i64.add\n i32.wrap_i64\n i32.store8\n";
  out << "          local.get $pos\n i32.const 1\n i32.sub\n local.set $pos\n";
  out << "          local.get $tmp\n i64.const 10\n i64.div_u\n local.set $tmp\n";
  out << "          br 0\n";
  out << "      end\n end\n";
  out << "    end\n";
  out << "    local.get $neg\n i32.const 0\n i32.ne\n";
  out << "    if\n";
  out << "      local.get $pos\n i32.const 45\n i32.store8\n";
  out << "      local.get $pos\n i32.const 1\n i32.sub\n local.set $pos\n";
  out << "    end\n";
  out << "    local.get $pos\n i32.const 1\n i32.add\n local.set $pos\n";
  out << "    i32.const " << (kBufPtr + 63) << "\n";
  out << "    local.get $pos\n i32.sub\n i32.const 1\n i32.add\n local.set $neg\n";
  out << "    local.get $pos\n local.get $neg\n call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_i64 (param $val i64)\n";
  out << "    local.get $val\n";
  out << "    call $print_i64_raw\n";
  out << "    i32.const " << (nl_ptr + 8) << "\n";
  out << "    i32.const 1\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $pow10_i64 (param $n i32) (result i64)\n";
  out << "    (local $res i64) (local $i i32)\n";
  out << "    i64.const 1\n";
  out << "    local.set $res\n";
  out << "    i32.const 0\n";
  out << "    local.set $i\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $i\n";
  out << "        local.get $n\n";
  out << "        i32.ge_u\n";
  out << "        br_if 1\n";
  out << "        local.get $res\n";
  out << "        i64.const 10\n";
  out << "        i64.mul\n";
  out << "        local.set $res\n";
  out << "        local.get $i\n";
  out << "        i32.const 1\n";
  out << "        i32.add\n";
  out << "        local.set $i\n";
  out << "        br 0\n";
  out << "      end\n";
  out << "    end\n";
  out << "    local.get $res\n";
  out << "  )\n";

  out << "  (func $print_fixed (param $val i64) (param $prec i32)\n";
  out << "    (local $i i32) (local $pos i32) (local $digit i64)\n";
  out << "    local.get $prec\n";
  out << "    i32.eqz\n";
  out << "    if\n";
  out << "      return\n";
  out << "    end\n";
  out << "    local.get $prec\n";
  out << "    i32.const 1\n";
  out << "    i32.sub\n";
  out << "    i32.const " << kFracBufPtr << "\n";
  out << "    i32.add\n";
  out << "    local.set $pos\n";
  out << "    i32.const 0\n";
  out << "    local.set $i\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $i\n";
  out << "        local.get $prec\n";
  out << "        i32.ge_u\n";
  out << "        br_if 1\n";
  out << "        local.get $val\n";
  out << "        i64.const 10\n";
  out << "        i64.rem_u\n";
  out << "        local.set $digit\n";
  out << "        local.get $pos\n";
  out << "        local.get $digit\n";
  out << "        i64.const 48\n";
  out << "        i64.add\n";
  out << "        i32.wrap_i64\n";
  out << "        i32.store8\n";
  out << "        local.get $val\n";
  out << "        i64.const 10\n";
  out << "        i64.div_u\n";
  out << "        local.set $val\n";
  out << "        local.get $pos\n";
  out << "        i32.const 1\n";
  out << "        i32.sub\n";
  out << "        local.set $pos\n";
  out << "        local.get $i\n";
  out << "        i32.const 1\n";
  out << "        i32.add\n";
  out << "        local.set $i\n";
  out << "        br 0\n";
  out << "      end\n";
  out << "    end\n";
  out << "    i32.const " << kFracBufPtr << "\n";
  out << "    local.get $prec\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_f64_prec (param $val f64) (param $prec i32)\n";
  out << "    (local $scale i64) (local $scaled i64) (local $int i64) (local $frac i64)\n";
  out << "    local.get $val\n";
  out << "    f64.const 0\n";
  out << "    f64.lt\n";
  out << "    if\n";
  out << "      i32.const 45\n";
  out << "      call $write_byte\n";
  out << "      local.get $val\n";
  out << "      f64.neg\n";
  out << "      local.set $val\n";
  out << "    end\n";
  out << "    local.get $prec\n";
  out << "    call $pow10_i64\n";
  out << "    local.set $scale\n";
  out << "    local.get $val\n";
  out << "    local.get $scale\n";
  out << "    f64.convert_i64_s\n";
  out << "    f64.mul\n";
  out << "    f64.const 0.5\n";
  out << "    f64.add\n";
  out << "    i64.trunc_f64_s\n";
  out << "    local.set $scaled\n";
  out << "    local.get $scaled\n";
  out << "    local.get $scale\n";
  out << "    i64.div_u\n";
  out << "    local.set $int\n";
  out << "    local.get $scaled\n";
  out << "    local.get $scale\n";
  out << "    i64.rem_u\n";
  out << "    local.set $frac\n";
  out << "    local.get $int\n";
  out << "    call $print_i64_raw\n";
  out << "    local.get $prec\n";
  out << "    i32.eqz\n";
  out << "    if\n";
  out << "    else\n";
  out << "      i32.const 46\n";
  out << "      call $write_byte\n";
  out << "      local.get $frac\n";
  out << "      local.get $prec\n";
  out << "      call $print_fixed\n";
  out << "    end\n";
  out << "  )\n";

  out << "  (func $print_f64_raw (param $val f64)\n";
  out << "    local.get $val\n";
  out << "    i32.const 6\n";
  out << "    call $print_f64_prec\n";
  out << "  )\n";

  out << "  (func $print_f64 (param $val f64)\n";
  out << "    local.get $val\n";
  out << "    call $print_f64_raw\n";
  out << "    i32.const " << (nl_ptr + 8) << "\n";
  out << "    i32.const 1\n";
  out << "    call $write_bytes\n";
  out << "  )\n";

  out << "  (func $print_f64_sci (param $val f64) (param $prec i32)\n";
  out << "    (local $exp i32)\n";
  out << "    local.get $val\n";
  out << "    f64.const 0\n";
  out << "    f64.lt\n";
  out << "    if\n";
  out << "      i32.const 45\n";
  out << "      call $write_byte\n";
  out << "      local.get $val\n";
  out << "      f64.neg\n";
  out << "      local.set $val\n";
  out << "    end\n";
  out << "    local.get $val\n";
  out << "    f64.const 0\n";
  out << "    f64.eq\n";
  out << "    if\n";
  out << "      f64.const 0\n";
  out << "      local.get $prec\n";
  out << "      call $print_f64_prec\n";
  out << "      i32.const 101\n";
  out << "      call $write_byte\n";
  out << "      i32.const 43\n";
  out << "      call $write_byte\n";
  out << "      i64.const 0\n";
  out << "      i32.const 2\n";
  out << "      call $print_fixed\n";
  out << "      return\n";
  out << "    end\n";
  out << "    i32.const 0\n";
  out << "    local.set $exp\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $val\n";
  out << "        f64.const 10\n";
  out << "        f64.ge\n";
  out << "        if\n";
  out << "          local.get $val\n";
  out << "          f64.const 10\n";
  out << "          f64.div\n";
  out << "          local.set $val\n";
  out << "          local.get $exp\n";
  out << "          i32.const 1\n";
  out << "          i32.add\n";
  out << "          local.set $exp\n";
  out << "          br 1\n";
  out << "        end\n";
  out << "        br 1\n";
  out << "      end\n";
  out << "    end\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $val\n";
  out << "        f64.const 1\n";
  out << "        f64.lt\n";
  out << "        if\n";
  out << "          local.get $val\n";
  out << "          f64.const 10\n";
  out << "          f64.mul\n";
  out << "          local.set $val\n";
  out << "          local.get $exp\n";
  out << "          i32.const 1\n";
  out << "          i32.sub\n";
  out << "          local.set $exp\n";
  out << "          br 1\n";
  out << "        end\n";
  out << "        br 1\n";
  out << "      end\n";
  out << "    end\n";
  out << "    local.get $val\n";
  out << "    local.get $prec\n";
  out << "    call $print_f64_prec\n";
  out << "    i32.const 101\n";
  out << "    call $write_byte\n";
  out << "    local.get $exp\n";
  out << "    i32.const 0\n";
  out << "    i32.lt_s\n";
  out << "    if\n";
  out << "      i32.const 45\n";
  out << "      call $write_byte\n";
  out << "      local.get $exp\n";
  out << "      i32.const -1\n";
  out << "      i32.mul\n";
  out << "      local.set $exp\n";
  out << "    else\n";
  out << "      i32.const 43\n";
  out << "      call $write_byte\n";
  out << "    end\n";
  out << "    local.get $exp\n";
  out << "    i64.extend_i32_u\n";
  out << "    i32.const 2\n";
  out << "    call $print_fixed\n";
  out << "  )\n";

  out << "  (func $print_format (param $fmt i64) (param $args i64) (param $count i32)\n";
  out << "    (local $len i32) (local $pos i32) (local $i i32) (local $arg_ptr i64)\n";
  out << "    (local $ch i32) (local $spec i32) (local $prec i32) (local $tmp i32)\n";
  out << "    local.get $fmt\n";
  out << "    i32.wrap_i64\n";
  out << "    i64.load\n";
  out << "    i32.wrap_i64\n";
  out << "    local.set $len\n";
  out << "    local.get $fmt\n";
  out << "    i64.const 8\n";
  out << "    i64.add\n";
  out << "    i32.wrap_i64\n";
  out << "    local.set $pos\n";
  out << "    local.get $args\n";
  out << "    local.set $arg_ptr\n";
  out << "    i32.const 0\n";
  out << "    local.set $i\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $i\n";
  out << "        local.get $len\n";
  out << "        i32.ge_u\n";
  out << "        br_if 1\n";
  out << "        local.get $pos\n";
  out << "        local.get $i\n";
  out << "        i32.add\n";
  out << "        i32.load8_u\n";
  out << "        local.set $ch\n";
  out << "        local.get $ch\n";
  out << "        i32.const 37\n";
  out << "        i32.eq\n";
  out << "        if\n";
  out << "          local.get $i\n";
  out << "          i32.const 1\n";
  out << "          i32.add\n";
  out << "          local.set $i\n";
  out << "          local.get $i\n";
  out << "          local.get $len\n";
  out << "          i32.ge_u\n";
  out << "          br_if 1\n";
  out << "          local.get $pos\n";
  out << "          local.get $i\n";
  out << "          i32.add\n";
  out << "          i32.load8_u\n";
  out << "          local.set $spec\n";
  out << "          local.get $spec\n";
  out << "          i32.const 37\n";
  out << "          i32.eq\n";
  out << "          if\n";
  out << "            i32.const 37\n";
  out << "            call $write_byte\n";
  out << "          else\n";
  out << "            i32.const 6\n";
  out << "            local.set $prec\n";
  out << "            local.get $spec\n";
  out << "            i32.const 114\n";
  out << "            i32.eq\n";
  out << "            local.get $spec\n";
  out << "            i32.const 101\n";
  out << "            i32.eq\n";
  out << "            i32.or\n";
  out << "            if\n";
  out << "              local.get $i\n";
  out << "              i32.const 1\n";
  out << "              i32.add\n";
  out << "              local.tee $tmp\n";
  out << "              local.get $len\n";
  out << "              i32.lt_u\n";
  out << "              if\n";
  out << "                local.get $pos\n";
  out << "                local.get $tmp\n";
  out << "                i32.add\n";
  out << "                i32.load8_u\n";
  out << "                i32.const 123\n";
  out << "                i32.eq\n";
  out << "                if\n";
  out << "                  i32.const 0\n";
  out << "                  local.set $prec\n";
  out << "                  local.get $tmp\n";
  out << "                  local.set $i\n";
  out << "                  block\n";
  out << "                    loop\n";
  out << "                      local.get $i\n";
  out << "                      i32.const 1\n";
  out << "                      i32.add\n";
  out << "                      local.set $i\n";
  out << "                      local.get $i\n";
  out << "                      local.get $len\n";
  out << "                      i32.ge_u\n";
  out << "                      br_if 1\n";
  out << "                      local.get $pos\n";
  out << "                      local.get $i\n";
  out << "                      i32.add\n";
  out << "                      i32.load8_u\n";
  out << "                      local.set $ch\n";
  out << "                      local.get $ch\n";
  out << "                      i32.const 125\n";
  out << "                      i32.eq\n";
  out << "                      br_if 1\n";
  out << "                      local.get $prec\n";
  out << "                      i32.const 10\n";
  out << "                      i32.mul\n";
  out << "                      local.get $ch\n";
  out << "                      i32.const 48\n";
  out << "                      i32.sub\n";
  out << "                      i32.add\n";
  out << "                      local.set $prec\n";
  out << "                      br 0\n";
  out << "                    end\n";
  out << "                  end\n";
  out << "                end\n";
  out << "              end\n";
  out << "            end\n";
  out << "            local.get $spec\n";
  out << "            i32.const 105\n";
  out << "            i32.eq\n";
  out << "            if\n";
  out << "              local.get $arg_ptr\n";
  out << "              i32.wrap_i64\n";
  out << "              i64.load\n";
  out << "              call $print_i64_raw\n";
  out << "              local.get $arg_ptr\n";
  out << "              i64.const 8\n";
  out << "              i64.add\n";
  out << "              local.set $arg_ptr\n";
  out << "            else\n";
  out << "              local.get $spec\n";
  out << "              i32.const 98\n";
  out << "              i32.eq\n";
  out << "              if\n";
  out << "                local.get $arg_ptr\n";
  out << "                i32.wrap_i64\n";
  out << "                i64.load\n";
  out << "                call $print_bool_raw\n";
  out << "                local.get $arg_ptr\n";
  out << "                i64.const 8\n";
  out << "                i64.add\n";
  out << "                local.set $arg_ptr\n";
  out << "              else\n";
  out << "                local.get $spec\n";
  out << "                i32.const 115\n";
  out << "                i32.eq\n";
  out << "                if\n";
  out << "                  local.get $arg_ptr\n";
  out << "                  i32.wrap_i64\n";
  out << "                  i64.load\n";
  out << "                  call $print_string_raw\n";
  out << "                  local.get $arg_ptr\n";
  out << "                  i64.const 8\n";
  out << "                  i64.add\n";
  out << "                  local.set $arg_ptr\n";
  out << "                else\n";
  out << "                  local.get $spec\n";
  out << "                  i32.const 114\n";
  out << "                  i32.eq\n";
  out << "                  if\n";
  out << "                    local.get $arg_ptr\n";
  out << "                    i32.wrap_i64\n";
  out << "                    f64.load\n";
  out << "                    local.get $prec\n";
  out << "                    call $print_f64_prec\n";
  out << "                    local.get $arg_ptr\n";
  out << "                    i64.const 8\n";
  out << "                    i64.add\n";
  out << "                    local.set $arg_ptr\n";
  out << "                  else\n";
  out << "                    local.get $spec\n";
  out << "                    i32.const 101\n";
  out << "                    i32.eq\n";
  out << "                    if\n";
  out << "                      local.get $arg_ptr\n";
  out << "                      i32.wrap_i64\n";
  out << "                      f64.load\n";
  out << "                      local.get $prec\n";
  out << "                      call $print_f64_sci\n";
  out << "                      local.get $arg_ptr\n";
  out << "                      i64.const 8\n";
  out << "                      i64.add\n";
  out << "                      local.set $arg_ptr\n";
  out << "                    end\n";
  out << "                  end\n";
  out << "                end\n";
  out << "              end\n";
  out << "            end\n";
  out << "          end\n";
  out << "        else\n";
  out << "          local.get $ch\n";
  out << "          call $write_byte\n";
  out << "        end\n";
  out << "        local.get $i\n";
  out << "        i32.const 1\n";
  out << "        i32.add\n";
  out << "        local.set $i\n";
  out << "        br 0\n";
  out << "      end\n";
  out << "    end\n";
  out << "  )\n";

  out << "  (func $build_args (result i64)\n";
  out << "    (local $sizes i32) (local $argc i32) (local $buf_size i32) (local $start i32)\n";
  out << "    (local $argv i32) (local $buf i32) (local $i i32) (local $ptr i32)\n";
  out << "    (local $len i32) (local $offset i32) (local $arr i64) (local $str i64)\n";
  out << "    i64.const 8\n";
  out << "    call $alloc\n";
  out << "    i32.wrap_i64\n";
  out << "    local.set $sizes\n";
  out << "    local.get $sizes\n";
  out << "    local.get $sizes\n";
  out << "    i32.const 4\n";
  out << "    i32.add\n";
  out << "    call $args_sizes_get\n";
  out << "    drop\n";
  out << "    local.get $sizes\n";
  out << "    i32.load\n";
  out << "    local.set $argc\n";
  out << "    i32.const 0\n";
  out << "    local.set $start\n";
  out << "    local.get $argc\n";
  out << "    i32.const 0\n";
  out << "    i32.gt_u\n";
  out << "    if\n";
  out << "      i32.const 1\n";
  out << "      local.set $start\n";
  out << "      local.get $argc\n";
  out << "      i32.const 1\n";
  out << "      i32.sub\n";
  out << "      local.set $argc\n";
  out << "    end\n";
  out << "    local.get $sizes\n";
  out << "    i32.const 4\n";
  out << "    i32.add\n";
  out << "    i32.load\n";
  out << "    local.set $buf_size\n";
  out << "    local.get $argc\n";
  out << "    i32.const 4\n";
  out << "    i32.mul\n";
  out << "    i64.extend_i32_u\n";
  out << "    call $alloc\n";
  out << "    i32.wrap_i64\n";
  out << "    local.set $argv\n";
  out << "    local.get $buf_size\n";
  out << "    i64.extend_i32_u\n";
  out << "    call $alloc\n";
  out << "    i32.wrap_i64\n";
  out << "    local.set $buf\n";
  out << "    local.get $argv\n";
  out << "    local.get $buf\n";
  out << "    call $args_get\n";
  out << "    drop\n";
  out << "    local.get $argc\n";
  out << "    i32.const 8\n";
  out << "    i32.mul\n";
  out << "    i32.const 8\n";
  out << "    i32.add\n";
  out << "    i64.extend_i32_u\n";
  out << "    call $alloc\n";
  out << "    local.set $arr\n";
  out << "    local.get $arr\n";
  out << "    i32.wrap_i64\n";
  out << "    local.get $argc\n";
  out << "    i64.extend_i32_u\n";
  out << "    i64.store\n";
  out << "    i32.const 0\n";
  out << "    local.set $i\n";
  out << "    block\n";
  out << "      loop\n";
  out << "        local.get $i\n";
  out << "        local.get $argc\n";
  out << "        i32.ge_u\n";
  out << "        br_if 1\n";
  out << "        local.get $argv\n";
  out << "        local.get $i\n";
  out << "        local.get $start\n";
  out << "        i32.add\n";
  out << "        i32.const 4\n";
  out << "        i32.mul\n";
  out << "        i32.add\n";
  out << "        i32.load\n";
  out << "        local.set $ptr\n";
  out << "        i32.const 0\n";
  out << "        local.set $len\n";
  out << "        block\n";
  out << "          loop\n";
  out << "            local.get $ptr\n";
  out << "            local.get $len\n";
  out << "            i32.add\n";
  out << "            i32.load8_u\n";
  out << "            i32.eqz\n";
  out << "            br_if 1\n";
  out << "            local.get $len\n";
  out << "            i32.const 1\n";
  out << "            i32.add\n";
  out << "            local.set $len\n";
  out << "            br 0\n";
  out << "          end\n";
  out << "        end\n";
  out << "        local.get $len\n";
  out << "        i32.const 8\n";
  out << "        i32.add\n";
  out << "        i64.extend_i32_u\n";
  out << "        call $alloc\n";
  out << "        local.set $str\n";
  out << "        local.get $str\n";
  out << "        i32.wrap_i64\n";
  out << "        local.get $len\n";
  out << "        i64.extend_i32_u\n";
  out << "        i64.store\n";
  out << "        i32.const 0\n";
  out << "        local.set $offset\n";
  out << "        block\n";
  out << "          loop\n";
  out << "            local.get $offset\n";
  out << "            local.get $len\n";
  out << "            i32.ge_u\n";
  out << "            br_if 1\n";
  out << "            local.get $str\n";
  out << "            i64.const 8\n";
  out << "            i64.add\n";
  out << "            i32.wrap_i64\n";
  out << "            local.get $offset\n";
  out << "            i32.add\n";
  out << "            local.get $ptr\n";
  out << "            local.get $offset\n";
  out << "            i32.add\n";
  out << "            i32.load8_u\n";
  out << "            i32.store8\n";
  out << "            local.get $offset\n";
  out << "            i32.const 1\n";
  out << "            i32.add\n";
  out << "            local.set $offset\n";
  out << "            br 0\n";
  out << "          end\n";
  out << "        end\n";
  out << "        local.get $arr\n";
  out << "        i64.const 8\n";
  out << "        i64.add\n";
  out << "        local.get $i\n";
  out << "        i64.extend_i32_u\n";
  out << "        i64.const 8\n";
  out << "        i64.mul\n";
  out << "        i64.add\n";
  out << "        i32.wrap_i64\n";
  out << "        local.get $str\n";
  out << "        i64.store\n";
  out << "        local.get $i\n";
  out << "        i32.const 1\n";
  out << "        i32.add\n";
  out << "        local.set $i\n";
  out << "        br 0\n";
  out << "      end\n";
  out << "    end\n";
  out << "    local.get $arr\n";
  out << "  )\n";

  out << "  (func $alloc (param $size i64) (result i64)\n";
  out << "    (local $aligned i64)\n";
  out << "    local.get $size\n";
  out << "    i64.const 7\n";
  out << "    i64.add\n";
  out << "    i64.const -8\n";
  out << "    i64.and\n";
  out << "    local.set $aligned\n";
  out << "    global.get $heap\n";
  out << "    local.get $aligned\n";
  out << "    i64.add\n";
  out << "    global.set $heap\n";
  out << "    global.get $heap\n";
  out << "    local.get $aligned\n";
  out << "    i64.sub\n";
  out << "  )\n";
}
