// THE BEER LICENSE (with extra fizz)
//
// Author: OpenAI Codex (controlled by jens@bennerhq.com)
// This code is open source with no restrictions. Wild, right?
// If this code helps, buy Jens a beer. Or two. Or a keg.
// If it fails, keep the beer and blame the LLM gremlins.
// Cheers!
#include "emitter_runtime.h"

RuntimeEmitter::RuntimeEmitter(std::ostream &out, const std::unordered_map<std::string, int64_t> &string_offsets)
    : out_(out), string_offsets_(string_offsets) {}

void RuntimeEmitter::Emit() {
    const int kIovecPtr = 0;
    const int kNwrittenPtr = 8;
    const int kBufPtr = 64;
    const int kFracBufPtr = 192;
    int64_t nl_ptr = string_offsets_.at("\n");
    int64_t dot_ptr = string_offsets_.at(".");
    int64_t minus_ptr = string_offsets_.at("-");
    int64_t plus_ptr = string_offsets_.at("+");
    int64_t e_ptr = string_offsets_.at("e");
    int64_t zero_ptr = string_offsets_.at("0");
    int64_t true_ptr = string_offsets_.at("true");
    int64_t false_ptr = string_offsets_.at("false");

    out_ << "  (func $write_bytes (param $ptr i32) (param $len i32)\n";
    out_ << "    i32.const " << kIovecPtr << "\n";
    out_ << "    local.get $ptr\n";
    out_ << "    i32.store\n";
    out_ << "    i32.const " << (kIovecPtr + 4) << "\n";
    out_ << "    local.get $len\n";
    out_ << "    i32.store\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.const " << kIovecPtr << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.const " << kNwrittenPtr << "\n";
    out_ << "    call $fd_write\n";
    out_ << "    drop\n";
    out_ << "  )\n";

    out_ << "  (func $print_string_raw (param $ptr i64)\n";
    out_ << "    (local $len i64)\n";
    out_ << "    local.get $ptr\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i64.load\n";
    out_ << "    local.set $len\n";
    out_ << "    local.get $ptr\n";
    out_ << "    i64.const 8\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.get $len\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_string (param $ptr i64)\n";
    out_ << "    local.get $ptr\n";
    out_ << "    call $print_string_raw\n";
    out_ << "    i32.const " << (nl_ptr + 8) << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_bool_raw (param $val i64)\n";
    out_ << "    local.get $val\n";
    out_ << "    i64.const 0\n";
    out_ << "    i64.ne\n";
    out_ << "    if\n";
    out_ << "      i32.const " << (true_ptr + 8) << "\n";
    out_ << "      i32.const 4\n";
    out_ << "      call $write_bytes\n";
    out_ << "    else\n";
    out_ << "      i32.const " << (false_ptr + 8) << "\n";
    out_ << "      i32.const 5\n";
    out_ << "      call $write_bytes\n";
    out_ << "    end\n";
    out_ << "  )\n";

    out_ << "  (func $print_bool (param $val i64)\n";
    out_ << "    local.get $val\n";
    out_ << "    call $print_bool_raw\n";
    out_ << "    i32.const " << (nl_ptr + 8) << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_i64_raw (param $val i64)\n";
    out_ << "    (local $tmp i64)\n";
    out_ << "    (local $pos i32)\n";
    out_ << "    (local $neg i32)\n";
    out_ << "    (local $digit i64)\n";
    out_ << "    i32.const " << (kBufPtr + 63) << "\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $val\n";
    out_ << "    i64.const 0\n";
    out_ << "    i64.lt_s\n";
    out_ << "    if\n";
    out_ << "      i32.const 1\n";
    out_ << "      local.set $neg\n";
    out_ << "      local.get $val\n";
    out_ << "      i64.const -1\n";
    out_ << "      i64.mul\n";
    out_ << "      local.set $tmp\n";
    out_ << "    else\n";
    out_ << "      i32.const 0\n";
    out_ << "      local.set $neg\n";
    out_ << "      local.get $val\n";
    out_ << "      local.set $tmp\n";
    out_ << "    end\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 0\n";
    out_ << "    i64.eq\n";
    out_ << "    if\n";
    out_ << "      local.get $pos\n";
    out_ << "      i32.const 48\n";
    out_ << "      i32.store8\n";
    out_ << "      local.get $pos\n";
    out_ << "      i32.const 1\n";
    out_ << "      i32.sub\n";
    out_ << "      local.set $pos\n";
    out_ << "    else\n";
    out_ << "      block\n";
    out_ << "        loop\n";
    out_ << "          local.get $tmp\n";
    out_ << "          i64.const 0\n";
    out_ << "          i64.eq\n";
    out_ << "          br_if 1\n";
    out_ << "          local.get $tmp\n";
    out_ << "          i64.const 10\n";
    out_ << "          i64.rem_u\n";
    out_ << "          local.set $digit\n";
    out_ << "          local.get $pos\n";
    out_ << "          local.get $digit\n";
    out_ << "          i64.const 48\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          i32.store8\n";
    out_ << "          local.get $pos\n";
    out_ << "          i32.const 1\n";
    out_ << "          i32.sub\n";
    out_ << "          local.set $pos\n";
    out_ << "          local.get $tmp\n";
    out_ << "          i64.const 10\n";
    out_ << "          i64.div_u\n";
    out_ << "          local.set $tmp\n";
    out_ << "          br 0\n";
    out_ << "        end\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "    local.get $neg\n";
    out_ << "    i32.const 0\n";
    out_ << "    i32.ne\n";
    out_ << "    if\n";
    out_ << "      local.get $pos\n";
    out_ << "      i32.const 45\n";
    out_ << "      i32.store8\n";
    out_ << "      local.get $pos\n";
    out_ << "      i32.const 1\n";
    out_ << "      i32.sub\n";
    out_ << "      local.set $pos\n";
    out_ << "    end\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    i32.const " << (kBufPtr + 63) << "\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.sub\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $neg\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $neg\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_i64 (param $val i64)\n";
    out_ << "    local.get $val\n";
    out_ << "    call $print_i64_raw\n";
    out_ << "    i32.const " << (nl_ptr + 8) << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_fixed6 (param $val i64)\n";
    out_ << "    (local $tmp i64)\n";
    out_ << "    (local $pos i32)\n";
    out_ << "    i32.const " << kFracBufPtr << "\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $val\n";
    out_ << "    local.set $tmp\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 100000\n";
    out_ << "    i64.div_u\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 10000\n";
    out_ << "    i64.div_u\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 1000\n";
    out_ << "    i64.div_u\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 100\n";
    out_ << "    i64.div_u\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.div_u\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.add\n";
    out_ << "    local.set $pos\n";
    out_ << "    local.get $pos\n";
    out_ << "    local.get $tmp\n";
    out_ << "    i64.const 10\n";
    out_ << "    i64.rem_u\n";
    out_ << "    i64.const 48\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i32.store8\n";
    out_ << "    i32.const " << kFracBufPtr << "\n";
    out_ << "    i32.const 6\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_f64_raw (param $val f64)\n";
    out_ << "    local.get $val\n";
    out_ << "    i32.const 6\n";
    out_ << "    call $print_f64_prec\n";
    out_ << "  )\n";

    out_ << "  (func $print_f64 (param $val f64)\n";
    out_ << "    local.get $val\n";
    out_ << "    call $print_f64_raw\n";
    out_ << "    i32.const " << (nl_ptr + 8) << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $pow10_i64 (param $n i32) (result i64)\n";
    out_ << "    (local $res i64)\n";
    out_ << "    i64.const 1\n";
    out_ << "    local.set $res\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $n\n";
    out_ << "        i32.eqz\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $res\n";
    out_ << "        i64.const 10\n";
    out_ << "        i64.mul\n";
    out_ << "        local.set $res\n";
    out_ << "        local.get $n\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.sub\n";
    out_ << "        local.set $n\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "    local.get $res\n";
    out_ << "  )\n";

    out_ << "  (func $print_fixed (param $val i64) (param $prec i32)\n";
    out_ << "    (local $pow i64)\n";
    out_ << "    (local $pos i32)\n";
    out_ << "    (local $digit i64)\n";
    out_ << "    local.get $prec\n";
    out_ << "    call $pow10_i64\n";
    out_ << "    local.set $pow\n";
    out_ << "    i32.const " << kFracBufPtr << "\n";
    out_ << "    local.set $pos\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $prec\n";
    out_ << "        i32.eqz\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $pow\n";
    out_ << "        i64.const 10\n";
    out_ << "        i64.div_u\n";
    out_ << "        local.set $pow\n";
    out_ << "        local.get $val\n";
    out_ << "        local.get $pow\n";
    out_ << "        i64.div_u\n";
    out_ << "        local.set $digit\n";
    out_ << "        local.get $val\n";
    out_ << "        local.get $pow\n";
    out_ << "        i64.rem_u\n";
    out_ << "        local.set $val\n";
    out_ << "        local.get $pos\n";
    out_ << "        local.get $digit\n";
    out_ << "        i64.const 48\n";
    out_ << "        i64.add\n";
    out_ << "        i32.wrap_i64\n";
    out_ << "        i32.store8\n";
    out_ << "        local.get $pos\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $pos\n";
    out_ << "        local.get $prec\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.sub\n";
    out_ << "        local.set $prec\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "    i32.const " << kFracBufPtr << "\n";
    out_ << "    local.get $pos\n";
    out_ << "    i32.const " << kFracBufPtr << "\n";
    out_ << "    i32.sub\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_f64_prec (param $val f64) (param $prec i32)\n";
    out_ << "    (local $abs f64)\n";
    out_ << "    (local $int i64)\n";
    out_ << "    (local $frac i64)\n";
    out_ << "    (local $scale i64)\n";
    out_ << "    local.get $val\n";
    out_ << "    f64.const 0\n";
    out_ << "    f64.lt\n";
    out_ << "    if\n";
    out_ << "      i32.const " << (minus_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      local.get $val\n";
    out_ << "      f64.const -1\n";
    out_ << "      f64.mul\n";
    out_ << "      local.set $abs\n";
    out_ << "    else\n";
    out_ << "      local.get $val\n";
    out_ << "      local.set $abs\n";
    out_ << "    end\n";
    out_ << "    local.get $abs\n";
    out_ << "    i64.trunc_f64_s\n";
    out_ << "    local.set $int\n";
    out_ << "    local.get $prec\n";
    out_ << "    call $pow10_i64\n";
    out_ << "    local.set $scale\n";
    out_ << "    local.get $abs\n";
    out_ << "    local.get $int\n";
    out_ << "    f64.convert_i64_s\n";
    out_ << "    f64.sub\n";
    out_ << "    local.get $scale\n";
    out_ << "    f64.convert_i64_s\n";
    out_ << "    f64.mul\n";
    out_ << "    f64.const 0.5\n";
    out_ << "    f64.add\n";
    out_ << "    i64.trunc_f64_s\n";
    out_ << "    local.set $frac\n";
    out_ << "    local.get $frac\n";
    out_ << "    local.get $scale\n";
    out_ << "    i64.eq\n";
    out_ << "    if\n";
    out_ << "      local.get $int\n";
    out_ << "      i64.const 1\n";
    out_ << "      i64.add\n";
    out_ << "      local.set $int\n";
    out_ << "      i64.const 0\n";
    out_ << "      local.set $frac\n";
    out_ << "    end\n";
    out_ << "    local.get $int\n";
    out_ << "    call $print_i64_raw\n";
    out_ << "    local.get $prec\n";
    out_ << "    i32.const 0\n";
    out_ << "    i32.gt_s\n";
    out_ << "    if\n";
    out_ << "      i32.const " << (dot_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      local.get $frac\n";
    out_ << "      local.get $prec\n";
    out_ << "      call $print_fixed\n";
    out_ << "    end\n";
    out_ << "  )\n";

    out_ << "  (func $print_f64_sci (param $val f64) (param $prec i32)\n";
    out_ << "    (local $abs f64)\n";
    out_ << "    (local $mant f64)\n";
    out_ << "    (local $exp i32)\n";
    out_ << "    local.get $val\n";
    out_ << "    f64.const 0\n";
    out_ << "    f64.lt\n";
    out_ << "    if\n";
    out_ << "      i32.const " << (minus_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      local.get $val\n";
    out_ << "      f64.const -1\n";
    out_ << "      f64.mul\n";
    out_ << "      local.set $abs\n";
    out_ << "    else\n";
    out_ << "      local.get $val\n";
    out_ << "      local.set $abs\n";
    out_ << "    end\n";
    out_ << "    local.get $abs\n";
    out_ << "    f64.const 0\n";
    out_ << "    f64.eq\n";
    out_ << "    if\n";
    out_ << "      f64.const 0\n";
    out_ << "      local.get $prec\n";
    out_ << "      call $print_f64_prec\n";
    out_ << "      i32.const " << (e_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      i32.const " << (plus_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      i32.const " << (zero_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      i32.const " << (zero_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "    else\n";
    out_ << "      local.get $abs\n";
    out_ << "      local.set $mant\n";
    out_ << "      i32.const 0\n";
    out_ << "      local.set $exp\n";
    out_ << "      block\n";
    out_ << "        loop\n";
    out_ << "          local.get $mant\n";
    out_ << "          f64.const 10\n";
    out_ << "          f64.ge\n";
    out_ << "          if\n";
    out_ << "            local.get $mant\n";
    out_ << "            f64.const 10\n";
    out_ << "            f64.div\n";
    out_ << "            local.set $mant\n";
    out_ << "            local.get $exp\n";
    out_ << "            i32.const 1\n";
    out_ << "            i32.add\n";
    out_ << "            local.set $exp\n";
    out_ << "            br 1\n";
    out_ << "          end\n";
    out_ << "        end\n";
    out_ << "      end\n";
    out_ << "      block\n";
    out_ << "        loop\n";
    out_ << "          local.get $mant\n";
    out_ << "          f64.const 1\n";
    out_ << "          f64.lt\n";
    out_ << "          if\n";
    out_ << "            local.get $mant\n";
    out_ << "            f64.const 10\n";
    out_ << "            f64.mul\n";
    out_ << "            local.set $mant\n";
    out_ << "            local.get $exp\n";
    out_ << "            i32.const 1\n";
    out_ << "            i32.sub\n";
    out_ << "            local.set $exp\n";
    out_ << "            br 1\n";
    out_ << "          end\n";
    out_ << "        end\n";
    out_ << "      end\n";
    out_ << "      local.get $mant\n";
    out_ << "      local.get $prec\n";
    out_ << "      call $print_f64_prec\n";
    out_ << "      i32.const " << (e_ptr + 8) << "\n";
    out_ << "      i32.const 1\n";
    out_ << "      call $write_bytes\n";
    out_ << "      local.get $exp\n";
    out_ << "      i32.const 0\n";
    out_ << "      i32.lt_s\n";
    out_ << "      if\n";
    out_ << "        i32.const " << (minus_ptr + 8) << "\n";
    out_ << "        i32.const 1\n";
    out_ << "        call $write_bytes\n";
    out_ << "        local.get $exp\n";
    out_ << "        i32.const -1\n";
    out_ << "        i32.mul\n";
    out_ << "        local.set $exp\n";
    out_ << "      else\n";
    out_ << "        i32.const " << (plus_ptr + 8) << "\n";
    out_ << "        i32.const 1\n";
    out_ << "        call $write_bytes\n";
    out_ << "      end\n";
    out_ << "      local.get $exp\n";
    out_ << "      i32.const 10\n";
    out_ << "      i32.lt_u\n";
    out_ << "      if\n";
    out_ << "        i32.const " << (zero_ptr + 8) << "\n";
    out_ << "        i32.const 1\n";
    out_ << "        call $write_bytes\n";
    out_ << "      end\n";
    out_ << "      local.get $exp\n";
    out_ << "      i64.extend_i32_u\n";
    out_ << "      call $print_i64_raw\n";
    out_ << "    end\n";
    out_ << "  )\n";

    out_ << "  (func $write_char (param $ch i32)\n";
    out_ << "    i32.const " << kBufPtr << "\n";
    out_ << "    local.get $ch\n";
    out_ << "    i32.store8\n";
    out_ << "    i32.const " << kBufPtr << "\n";
    out_ << "    i32.const 1\n";
    out_ << "    call $write_bytes\n";
    out_ << "  )\n";

    out_ << "  (func $print_format (param $fmt i64) (param $args i64) (param $count i32)\n";
    out_ << "    (local $len i32)\n";
    out_ << "    (local $base i32)\n";
    out_ << "    (local $i i32)\n";
    out_ << "    (local $arg i32)\n";
    out_ << "    (local $ch i32)\n";
    out_ << "    (local $spec i32)\n";
    out_ << "    (local $prec i32)\n";
    out_ << "    (local $arg_ptr i64)\n";
    out_ << "    (local $tag i32)\n";
    out_ << "    local.get $fmt\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    i64.load\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.set $len\n";
    out_ << "    local.get $fmt\n";
    out_ << "    i64.const 8\n";
    out_ << "    i64.add\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.set $base\n";
    out_ << "    i32.const 0\n";
    out_ << "    local.set $i\n";
    out_ << "    i32.const 0\n";
    out_ << "    local.set $arg\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $i\n";
    out_ << "        local.get $len\n";
    out_ << "        i32.ge_u\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $base\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.add\n";
    out_ << "        i32.load8_u\n";
    out_ << "        local.set $ch\n";
    out_ << "        local.get $ch\n";
    out_ << "        i32.const 37\n";
    out_ << "        i32.ne\n";
    out_ << "        if\n";
    out_ << "          local.get $ch\n";
    out_ << "          call $write_char\n";
    out_ << "          local.get $i\n";
    out_ << "          i32.const 1\n";
    out_ << "          i32.add\n";
    out_ << "          local.set $i\n";
    out_ << "          br 1\n";
    out_ << "        end\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $i\n";
    out_ << "        local.get $i\n";
    out_ << "        local.get $len\n";
    out_ << "        i32.ge_u\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $base\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.add\n";
    out_ << "        i32.load8_u\n";
    out_ << "        local.set $spec\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 37\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          i32.const 37\n";
    out_ << "          call $write_char\n";
    out_ << "          local.get $i\n";
    out_ << "          i32.const 1\n";
    out_ << "          i32.add\n";
    out_ << "          local.set $i\n";
    out_ << "          br 0\n";
    out_ << "        end\n";
    out_ << "        local.get $arg\n";
    out_ << "        local.get $count\n";
    out_ << "        i32.ge_u\n";
    out_ << "        br_if 1\n";
    out_ << "        i32.const 6\n";
    out_ << "        local.set $prec\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 114\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $i\n";
    out_ << "          i32.const 1\n";
    out_ << "          i32.add\n";
    out_ << "          local.set $ch\n";
    out_ << "          local.get $ch\n";
    out_ << "          local.get $len\n";
    out_ << "          i32.lt_u\n";
    out_ << "          if\n";
    out_ << "            local.get $base\n";
    out_ << "            local.get $ch\n";
    out_ << "            i32.add\n";
    out_ << "            i32.load8_u\n";
    out_ << "            i32.const 123\n";
    out_ << "            i32.eq\n";
    out_ << "            if\n";
    out_ << "              local.get $ch\n";
    out_ << "              local.set $i\n";
    out_ << "              i32.const 0\n";
    out_ << "              local.set $prec\n";
    out_ << "              block\n";
    out_ << "                loop\n";
    out_ << "                  local.get $i\n";
    out_ << "                  i32.const 1\n";
    out_ << "                  i32.add\n";
    out_ << "                  local.set $i\n";
    out_ << "                  local.get $i\n";
    out_ << "                  local.get $len\n";
    out_ << "                  i32.ge_u\n";
    out_ << "                  br_if 2\n";
    out_ << "                  local.get $base\n";
    out_ << "                  local.get $i\n";
    out_ << "                  i32.add\n";
    out_ << "                  i32.load8_u\n";
    out_ << "                  local.set $ch\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.const 125\n";
    out_ << "                  i32.eq\n";
    out_ << "                  br_if 1\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.const 48\n";
    out_ << "                  i32.sub\n";
    out_ << "                  local.set $ch\n";
    out_ << "                  local.get $prec\n";
    out_ << "                  i32.const 10\n";
    out_ << "                  i32.mul\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.add\n";
    out_ << "                  local.set $prec\n";
    out_ << "                  br 0\n";
    out_ << "                end\n";
    out_ << "              end\n";
    out_ << "            end\n";
    out_ << "          end\n";
    out_ << "        end\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 101\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $i\n";
    out_ << "          i32.const 1\n";
    out_ << "          i32.add\n";
    out_ << "          local.set $ch\n";
    out_ << "          local.get $ch\n";
    out_ << "          local.get $len\n";
    out_ << "          i32.lt_u\n";
    out_ << "          if\n";
    out_ << "            local.get $base\n";
    out_ << "            local.get $ch\n";
    out_ << "            i32.add\n";
    out_ << "            i32.load8_u\n";
    out_ << "            i32.const 123\n";
    out_ << "            i32.eq\n";
    out_ << "            if\n";
    out_ << "              local.get $ch\n";
    out_ << "              local.set $i\n";
    out_ << "              i32.const 0\n";
    out_ << "              local.set $prec\n";
    out_ << "              block\n";
    out_ << "                loop\n";
    out_ << "                  local.get $i\n";
    out_ << "                  i32.const 1\n";
    out_ << "                  i32.add\n";
    out_ << "                  local.set $i\n";
    out_ << "                  local.get $i\n";
    out_ << "                  local.get $len\n";
    out_ << "                  i32.ge_u\n";
    out_ << "                  br_if 2\n";
    out_ << "                  local.get $base\n";
    out_ << "                  local.get $i\n";
    out_ << "                  i32.add\n";
    out_ << "                  i32.load8_u\n";
    out_ << "                  local.set $ch\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.const 125\n";
    out_ << "                  i32.eq\n";
    out_ << "                  br_if 1\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.const 48\n";
    out_ << "                  i32.sub\n";
    out_ << "                  local.set $ch\n";
    out_ << "                  local.get $prec\n";
    out_ << "                  i32.const 10\n";
    out_ << "                  i32.mul\n";
    out_ << "                  local.get $ch\n";
    out_ << "                  i32.add\n";
    out_ << "                  local.set $prec\n";
    out_ << "                  br 0\n";
    out_ << "                end\n";
    out_ << "              end\n";
    out_ << "            end\n";
    out_ << "          end\n";
    out_ << "        end\n";
    out_ << "        local.get $args\n";
    out_ << "        local.get $arg\n";
    out_ << "        i32.const 16\n";
    out_ << "        i32.mul\n";
    out_ << "        i64.extend_i32_u\n";
    out_ << "        i64.add\n";
    out_ << "        local.set $arg_ptr\n";
    out_ << "        local.get $arg_ptr\n";
    out_ << "        i32.wrap_i64\n";
    out_ << "        i32.load\n";
    out_ << "        local.set $tag\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 105\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $arg_ptr\n";
    out_ << "          i64.const 8\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          i64.load\n";
    out_ << "          call $print_i64_raw\n";
    out_ << "        end\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 98\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $arg_ptr\n";
    out_ << "          i64.const 8\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          i64.load\n";
    out_ << "          call $print_bool_raw\n";
    out_ << "        end\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 115\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $arg_ptr\n";
    out_ << "          i64.const 8\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          i64.load\n";
    out_ << "          call $print_string_raw\n";
    out_ << "        end\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 114\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $arg_ptr\n";
    out_ << "          i64.const 8\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          f64.load\n";
    out_ << "          local.get $prec\n";
    out_ << "          call $print_f64_prec\n";
    out_ << "        end\n";
    out_ << "        local.get $spec\n";
    out_ << "        i32.const 101\n";
    out_ << "        i32.eq\n";
    out_ << "        if\n";
    out_ << "          local.get $arg_ptr\n";
    out_ << "          i64.const 8\n";
    out_ << "          i64.add\n";
    out_ << "          i32.wrap_i64\n";
    out_ << "          f64.load\n";
    out_ << "          local.get $prec\n";
    out_ << "          call $print_f64_sci\n";
    out_ << "        end\n";
    out_ << "        local.get $arg\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $arg\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $i\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "  )\n";

    out_ << "  (func $strlen (param $ptr i32) (result i32)\n";
    out_ << "    (local $p i32)\n";
    out_ << "    (local $len i32)\n";
    out_ << "    local.get $ptr\n";
    out_ << "    local.set $p\n";
    out_ << "    i32.const 0\n";
    out_ << "    local.set $len\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $p\n";
    out_ << "        i32.load8_u\n";
    out_ << "        i32.eqz\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $p\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $p\n";
    out_ << "        local.get $len\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $len\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "    local.get $len\n";
    out_ << "  )\n";

    out_ << "  (func $memcpy (param $dst i32) (param $src i32) (param $len i32)\n";
    out_ << "    (local $i i32)\n";
    out_ << "    i32.const 0\n";
    out_ << "    local.set $i\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $i\n";
    out_ << "        local.get $len\n";
    out_ << "        i32.ge_u\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $dst\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.add\n";
    out_ << "        local.get $src\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.add\n";
    out_ << "        i32.load8_u\n";
    out_ << "        i32.store8\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $i\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "  )\n";

    out_ << "  (func $build_args (result i64)\n";
    out_ << "    (local $argc i32)\n";
    out_ << "    (local $bufsz i32)\n";
    out_ << "    (local $argv_ptrs i32)\n";
    out_ << "    (local $argv_buf i32)\n";
    out_ << "    (local $arr i64)\n";
    out_ << "    (local $count i32)\n";
    out_ << "    (local $i i32)\n";
    out_ << "    (local $ptr i32)\n";
    out_ << "    (local $len i32)\n";
    out_ << "    (local $str i64)\n";
    out_ << "    (local $dst i32)\n";
    out_ << "    i32.const 16\n";
    out_ << "    i32.const 20\n";
    out_ << "    call $args_sizes_get\n";
    out_ << "    drop\n";
    out_ << "    i32.const 16\n";
    out_ << "    i32.load\n";
    out_ << "    local.set $argc\n";
    out_ << "    i32.const 20\n";
    out_ << "    i32.load\n";
    out_ << "    local.set $bufsz\n";
    out_ << "    local.get $argc\n";
    out_ << "    i32.eqz\n";
    out_ << "    if\n";
    out_ << "      i64.const 8\n";
    out_ << "      call $alloc\n";
    out_ << "      local.set $arr\n";
    out_ << "      local.get $arr\n";
    out_ << "      i32.wrap_i64\n";
    out_ << "      i64.const 0\n";
    out_ << "      i64.store\n";
    out_ << "      local.get $arr\n";
    out_ << "      return\n";
    out_ << "    end\n";
    out_ << "    local.get $argc\n";
    out_ << "    i64.extend_i32_u\n";
    out_ << "    i64.const 4\n";
    out_ << "    i64.mul\n";
    out_ << "    call $alloc\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.set $argv_ptrs\n";
    out_ << "    local.get $bufsz\n";
    out_ << "    i64.extend_i32_u\n";
    out_ << "    call $alloc\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.set $argv_buf\n";
    out_ << "    local.get $argv_ptrs\n";
    out_ << "    local.get $argv_buf\n";
    out_ << "    call $args_get\n";
    out_ << "    drop\n";
    out_ << "    local.get $argc\n";
    out_ << "    i32.const 1\n";
    out_ << "    i32.sub\n";
    out_ << "    local.set $count\n";
    out_ << "    local.get $count\n";
    out_ << "    i64.extend_i32_u\n";
    out_ << "    i64.const 8\n";
    out_ << "    i64.mul\n";
    out_ << "    i64.const 8\n";
    out_ << "    i64.add\n";
    out_ << "    call $alloc\n";
    out_ << "    local.set $arr\n";
    out_ << "    local.get $arr\n";
    out_ << "    i32.wrap_i64\n";
    out_ << "    local.get $count\n";
    out_ << "    i64.extend_i32_u\n";
    out_ << "    i64.store\n";
    out_ << "    i32.const 0\n";
    out_ << "    local.set $i\n";
    out_ << "    block\n";
    out_ << "      loop\n";
    out_ << "        local.get $i\n";
    out_ << "        local.get $count\n";
    out_ << "        i32.ge_u\n";
    out_ << "        br_if 1\n";
    out_ << "        local.get $argv_ptrs\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        i32.const 4\n";
    out_ << "        i32.mul\n";
    out_ << "        i32.add\n";
    out_ << "        i32.load\n";
    out_ << "        local.set $ptr\n";
    out_ << "        local.get $ptr\n";
    out_ << "        call $strlen\n";
    out_ << "        local.set $len\n";
    out_ << "        local.get $len\n";
    out_ << "        i64.extend_i32_u\n";
    out_ << "        i64.const 8\n";
    out_ << "        i64.add\n";
    out_ << "        call $alloc\n";
    out_ << "        local.set $str\n";
    out_ << "        local.get $str\n";
    out_ << "        i32.wrap_i64\n";
    out_ << "        local.get $len\n";
    out_ << "        i64.extend_i32_u\n";
    out_ << "        i64.store\n";
    out_ << "        local.get $str\n";
    out_ << "        i64.const 8\n";
    out_ << "        i64.add\n";
    out_ << "        i32.wrap_i64\n";
    out_ << "        local.set $dst\n";
    out_ << "        local.get $dst\n";
    out_ << "        local.get $ptr\n";
    out_ << "        local.get $len\n";
    out_ << "        call $memcpy\n";
    out_ << "        local.get $arr\n";
    out_ << "        i64.const 8\n";
    out_ << "        i64.add\n";
    out_ << "        local.get $i\n";
    out_ << "        i64.extend_i32_u\n";
    out_ << "        i64.const 8\n";
    out_ << "        i64.mul\n";
    out_ << "        i64.add\n";
    out_ << "        i32.wrap_i64\n";
    out_ << "        local.get $str\n";
    out_ << "        i64.store\n";
    out_ << "        local.get $i\n";
    out_ << "        i32.const 1\n";
    out_ << "        i32.add\n";
    out_ << "        local.set $i\n";
    out_ << "        br 0\n";
    out_ << "      end\n";
    out_ << "    end\n";
    out_ << "    local.get $arr\n";
    out_ << "  )\n";

    out_ << "  (func $alloc (param $size i64) (result i64)\n";
    out_ << "    (local $old i64)\n";
    out_ << "    (local $new i64)\n";
    out_ << "    (local $cur_bytes i64)\n";
    out_ << "    (local $need_bytes i64)\n";
    out_ << "    (local $pages i32)\n";
    out_ << "    global.get $heap\n";
    out_ << "    local.set $old\n";
    out_ << "    global.get $heap\n";
    out_ << "    local.get $size\n";
    out_ << "    i64.add\n";
    out_ << "    local.set $new\n";
    out_ << "    memory.size\n";
    out_ << "    i64.extend_i32_u\n";
    out_ << "    i64.const 65536\n";
    out_ << "    i64.mul\n";
    out_ << "    local.set $cur_bytes\n";
    out_ << "    local.get $new\n";
    out_ << "    local.get $cur_bytes\n";
    out_ << "    i64.gt_u\n";
    out_ << "    if\n";
    out_ << "      local.get $new\n";
    out_ << "      local.get $cur_bytes\n";
    out_ << "      i64.sub\n";
    out_ << "      i64.const 65535\n";
    out_ << "      i64.add\n";
    out_ << "      i64.const 65536\n";
    out_ << "      i64.div_u\n";
    out_ << "      i32.wrap_i64\n";
    out_ << "      local.set $pages\n";
    out_ << "      local.get $pages\n";
    out_ << "      memory.grow\n";
    out_ << "      drop\n";
    out_ << "    end\n";
    out_ << "    local.get $new\n";
    out_ << "    global.set $heap\n";
    out_ << "    local.get $old\n";
    out_ << "  )\n";
}
